name: Build ExCSS
agent:
    type: Unity::VM
    image: build-system/unity-extra-windows-10:latest
    flavor: b1.large

artifacts:
    builds:
        paths:
            - builds/**

commands:
    - build.bat
