name: Build ExCSS
agent:
    type: Unity::VM
    image: build-system/unity-extra-windows-10:latest
    flavor: b1.large

artifacts:
    builds:
        paths:
            - builds/**

commands:
    - gsudo.exe choco install dotnet-8.0-sdk -y 
    - dotnet build "ExCSS.sln" -c Release
    - dotnet test "ExCSS.sln" -c Release
    - mkdir .\builds\lib\netstandard2.0 
    - del .\src\ExCSS\bin\Release\netstandard2.0\ExCSS.Unity.deps.json
    - copy .\src\ExCSS\bin\Release\netstandard2.0\*.* .\builds\lib\netstandard2.0

