name: build
on:
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic version
        uses: './.github/actions/dotnet/version'
        id: version

      - name: Restore and build zip
        uses: './.github/actions/dotnet/build'

      - name: Execute unit test and publish reports
        uses: './.github/actions/dotnet/test'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
